---
seeds:
  seeds_blurb: 'Customize this text to explain how your game uses the Seeds code.'
  shortcuts:
    seeds/update: seeds/set
    seed: seeds
    seeds/remove: seeds/delete
    seeds/add: seeds/new
  permissions:
    manage_seeds: View and edit Seeds details on other chars.